apiVersion: v1
kind: Pod
metadata:
  name: bash
spec:
  containers:
    - name: bash1
      image: bash:4.4
      command:
        - sh
        - -c
        - | {{ .Values.commandBlock | nindent 10 }}
    - name: bash2
      image: bash:4.4
      command:
        - sh
        - -c
        - "{{ .Values.commandFoldedBlock }}"
    - name: bash3
      image: bash:4.4
      command: {{ toYaml .Values.commandList | nindent 8 }}
    - name: bash4
      image: bash:4.4
      command: {{ toYaml .Values.commandListWithFoldedBlock | nindent 8 }}
    - name: bash5
      image: bash:4.4
      command:
        - sh
        - -c
      args: {{ toYaml .Values.argsList | nindent 8 }}

